export const toolOptions = [
  { label: 'JavaScript', value: 'JavaScript' },
  { label: 'TypeScript', value: 'TypeScript' },
  { label: 'React', value: 'React' },
  { label: 'Redux', value: 'Redux' },
  { label: 'Node.js', value: 'Nodejs' },
  { label: 'Java', value: 'Java' },
  { label: 'Spring Boot', value: 'SpringBoot' },
  { label: 'Python', value: 'Python' },
  { label: 'Flutter', value: 'Flutter' },
  { label: 'Ruby on Rails', value: 'RubyOnRails' },
  { label: 'Next.js', value: 'Next' },
  { label: 'HTML', value: 'HTML' },
  { label: 'CSS', value: 'CSS' },
  { label: 'MySQL', value: 'MySQL' },
  { label: 'PostgreSQL', value: 'Postgres' },
  { label: 'Firebase', value: 'Firebase' },
  { label: 'C', value: 'C' },
  { label: 'Go', value: 'Go' },
] as const
